spring:
  application:
    name: fiap-pagamento-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pagamento-service}${DB_URL_PARAM:?ssl=false}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
    jpa:
      show-sql: true
      hibernate:
        generate-ddl: true
        ddl-auto: update

mock:
  mercado-pago:
    enabled: true

client:
  mercadopago:
    token: ${MERCADOPAGO_TOKEN:TEST-8560186811425402-042821-5380eeb105625d0ea6737dc380ffe158-57534286}
    url: ${MERCADOPAGO_URL:https://api.mercadopago.com/v1}
    public-key: ${MERCADOPAGO_PUBLIC_KEY:TEST-2bb25cd7-97df-4278-b1f9-01464bf15805}
  cliente-service:
    url: ${CLIENTE_SERVICE_URL:http://localhost:8081}

server:
  port: 8083
