name: CI Pipeline with Dockerfile

on:
  push:
    branches:
      - master  # Build automático ao enviar código para a branch "master"
  workflow_dispatch:  # Deploy manual

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # Especifica o environment "production" para este job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Configurar o JDK 17
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      # Step 2: Build com Maven usando o JDK 17
      - name: Build with Maven
        run: mvn clean install

      # Step 3: Build imagem docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      # Step 4: Login no docker hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Push imagem docker para o Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
